### ISSUE TITLE
this.adapter.persistSession is not a function

### ISSUE THREAD

**Issue by MichaelJCole** [socketio/socket.io-mongo-adapter#12]
Hi, I'm getting this error:

```
/home/app/node_modules/socket.io/dist/socket.js:550
            this.adapter.persistSession({
                         ^
TypeError: this.adapter.persistSession is not a function
    at Socket._onclose (/home/app/node_modules/socket.io/dist/socket.js:550:26)
    at Client.onclose (/home/app/node_modules/socket.io/dist/client.js:247:20)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at Socket.onClose (/home/app/node_modules/engine.io/build/socket.js:304:18)
    at Timeout.<anonymous> (/home/app/node_modules/engine.io/build/socket.js:154:18)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
error Command failed with exit code 1.
```

I'm using the adapter with `"socket.io": "^4.6.0",` with a capped collection as described in the README.  I see the collection and hundreds of documents.

I'm using it with express-sessions.  It was working pretty well until I added the adapter.
```
const mongoCollection = connection.getClient().db(connection.name).collection(COLLECTION)
  const adapter = createAdapter(mongoCollection)

  logDebug('Configuring io server')
  io = new Server<ClientToServerEvents, ServerToClientEvents, InterServerEvents, SocketData>(http, {
    serveClient: false,
    path: SOCKET_IO_PATH,
    connectionStateRecovery: {
      // the backup duration of the sessions and the packets
      maxDisconnectionDuration: 2 * 60 * 1000,
      // whether to skip middlewares upon successful recovery
      //skipMiddlewares: true,
    },
  })
  // @ts-ignore https://socket.io/docs/v4/mongo-adapter/
  io.adapter(adapter)
  io.engine.use(sessions)
```

The `@ts-ignore` is for a type issue.  io.adapter wants a `AdapterConstructor`.  `createAdapter` returns a `MongoAdapter`.

I got this code pattern from the readme. https://github.com/socketio/socket.io-mongo-adapter#usage-with-a-capped-collection

Am I using it correctly?  Does the package need an update to work with 4.6?  

Thank you,  Michael

**Comment by darrachequesne** [comment]
Hi Michael,

Support for the connection state recovery was added in version [0.3.0](https://github.com/socketio/socket.io-mongo-adapter/releases/tag/0.3.0), which was released a few minutes ago.

Have a great day!

**Comment by MichaelJCole** [comment]
Thank you!
